/*
*@Author:ferried
*@Email:harlancui@outlook.com
*@Date:2020-11-1811:39:11
 * @LastEditTime: 2020-11-18 14:02:59
 * @LastEditors: ferried
*@Description:Basicdescription
 * @FilePath: /redis-prometheus-dashboard/metrics/metrics_rules.go
*@LICENSE:Apache-2.0
*/

package metrics

var metricsPromqlMap = map[string]string{
	"redis_active_defrag_running":                     "redis_active_defrag_running",
	"redis_aof_current_rewrite_duration_sec":          "redis_aof_current_rewrite_duration_sec",
	"redis_aof_enabled":                               "redis_aof_enabled",
	"redis_aof_last_bgrewrite_status":                 "redis_aof_last_bgrewrite_status",
	"redis_aof_last_cow_size_bytes":                   "redis_aof_last_cow_size_bytes",
	"redis_aof_last_rewrite_duration_sec":             "redis_aof_last_rewrite_duration_sec",
	"redis_aof_last_write_status":                     "redis_aof_last_write_status",
	"redis_aof_rewrite_in_progress":                   "redis_aof_rewrite_in_progress",
	"redis_aof_rewrite_scheduled":                     "redis_aof_rewrite_scheduled",
	"redis_blocked_clients":                           "redis_blocked_clients",
	"redis_client_biggest_input_buf":                  "redis_client_biggest_input_buf",
	"redis_client_longest_output_list":                "redis_client_longest_output_list",
	"redis_cluster_enabled":                           "redis_cluster_enabled",
	"redis_commands_duration_seconds_total":           "redis_commands_duration_seconds_total",
	"redis_commands_processed_total":                  "redis_commands_processed_total",
	"redis_commands_total":                            "redis_commands_total",
	"redis_config_maxclients":                         "redis_config_maxclients",
	"redis_config_maxmemory":                          "redis_config_maxmemory",
	"redis_connected_clients":                         "redis_connected_clients",
	"redis_connected_slaves":                          "redis_connected_slaves",
	"redis_connections_received_total":                "redis_connections_received_total",
	"redis_cpu_sys_children_seconds_total":            "redis_cpu_sys_children_seconds_total",
	"redis_cpu_sys_seconds_total":                     "redis_cpu_sys_seconds_total",
	"redis_cpu_user_children_seconds_total":           "redis_cpu_user_children_seconds_total",
	"redis_cpu_user_seconds_total":                    "redis_cpu_user_seconds_total",
	"redis_db_avg_ttl_seconds":                        "redis_db_avg_ttl_seconds",
	"redis_db_keys":                                   "redis_db_keys",
	"redis_db_keys_expiring":                          "redis_db_keys_expiring",
	"redis_defrag_hits":                               "redis_defrag_hits",
	"redis_defrag_key_hits":                           "redis_defrag_key_hits",
	"redis_defrag_key_misses":                         "redis_defrag_key_misses",
	"redis_defrag_misses":                             "redis_defrag_misses",
	"redis_evicted_keys_total":                        "redis_evicted_keys_total",
	"redis_expired_time_cap_reached_total":            "redis_expired_time_cap_reached_total",
	"redis_exporter_build_info":                       "redis_exporter_build_info",
	"redis_exporter_last_scrape_connect_time_seconds": "redis_exporter_last_scrape_connect_time_seconds",
	"redis_exporter_last_scrape_duration_seconds":     "redis_exporter_last_scrape_duration_seconds",
	"redis_exporter_last_scrape_error":                "redis_exporter_last_scrape_error",
	"redis_exporter_scrape_duration_seconds_count":    "redis_exporter_scrape_duration_seconds_count",
	"redis_exporter_scrape_duration_seconds_sum":      "redis_exporter_scrape_duration_seconds_sum",
	"redis_exporter_scrapes_total":                    "redis_exporter_scrapes_total",
	"redis_instance_info":                             "redis_instance_info",
	"redis_keyspace_hits_total":                       "redis_keyspace_hits_total",
	"redis_keyspace_misses_total":                     "redis_keyspace_misses_total",
	"redis_last_slow_execution_duration_seconds":      "redis_last_slow_execution_duration_seconds",
	"redis_latest_fork_seconds":                       "redis_latest_fork_seconds",
	"redis_lazyfree_pending_objects":                  "redis_lazyfree_pending_objects",
	"redis_loading_dump_file":                         "redis_loading_dump_file",
	"redis_master_repl_offset":                        "redis_master_repl_offset",
	"redis_mem_fragmentation_ratio":                   "redis_mem_fragmentation_ratio",
	"redis_memory_max_bytes":                          "redis_memory_max_bytes",
	"redis_memory_used_bytes":                         "redis_memory_used_bytes",
	"redis_memory_used_bytesredis_memory_max_bytes":   "redis_memory_used_bytesredis_memory_max_bytes",
	"redis_memory_used_dataset_bytes":                 "redis_memory_used_dataset_bytes",
	"redis_memory_used_lua_bytes":                     "redis_memory_used_lua_bytes",
	"redis_memory_used_overhead_bytes":                "redis_memory_used_overhead_bytes",
	"redis_memory_used_peak_bytes":                    "redis_memory_used_peak_bytes",
	"redis_memory_used_rss_bytes":                     "redis_memory_used_rss_bytes",
	"redis_memory_used_startup_bytes":                 "redis_memory_used_startup_bytes",
	"redis_migrate_cached_sockets_total":              "redis_migrate_cached_sockets_total",
	"redis_net_input_bytes_total":                     "redis_net_input_bytes_total",
	"redis_net_output_bytes_total":                    "redis_net_output_bytes_total",
	"redis_process_id":                                "redis_process_id",
	"redis_process_id:node_memory_utilisation:":       "redis_process_id:node_memory_utilisation:",
	"redis_pubsub_channels":                           "redis_pubsub_channels",
	"redis_pubsub_patterns":                           "redis_pubsub_patterns",
	"redis_rdb_bgsave_in_progress":                    "redis_rdb_bgsave_in_progress",
	"redis_rdb_changes_since_last_save":               "redis_rdb_changes_since_last_save",
	"redis_rdb_current_bgsave_duration_sec":           "redis_rdb_current_bgsave_duration_sec",
	"redis_rdb_last_bgsave_duration_sec":              "redis_rdb_last_bgsave_duration_sec",
	"redis_rdb_last_bgsave_status":                    "redis_rdb_last_bgsave_status",
	"redis_rdb_last_cow_size_bytes":                   "redis_rdb_last_cow_size_bytes",
	"redis_rdb_last_save_timestamp_seconds":           "redis_rdb_last_save_timestamp_seconds",
	"redis_rejected_connections_total":                "redis_rejected_connections_total",
	"redis_repl_backlog_first_byte_offset":            "redis_repl_backlog_first_byte_offset",
	"redis_repl_backlog_history_bytes":                "redis_repl_backlog_history_bytes",
	"redis_repl_backlog_is_active":                    "redis_repl_backlog_is_active",
	"redis_replica_partial_resync_accepted":           "redis_replica_partial_resync_accepted",
	"redis_replica_partial_resync_denied":             "redis_replica_partial_resync_denied",
	"redis_replica_resyncs_full":                      "redis_replica_resyncs_full",
	"redis_replication_backlog_bytes":                 "redis_replication_backlog_bytes",
	"redis_second_repl_offset":                        "redis_second_repl_offset",
	"redis_slave_expires_tracked_keys":                "redis_slave_expires_tracked_keys",
	"redis_slowlog_last_id":                           "redis_slowlog_last_id",
	"redis_slowlog_length":                            "redis_slowlog_length",
	"redis_start_time_seconds":                        "redis_start_time_seconds",
	"redis_target_scrape_request_errors_total":        "redis_target_scrape_request_errors_total",
	"redis_up":                "redis_up",
	"redis_uptime_in_seconds": "redis_uptime_in_seconds",
}
